
adjective1 = input("An Adjective:")
noun = input("A Noun:")
adjective2 = input("An Adjective:")
feeling_ending_in_ed = input("Feeling ending in -ed:")
name = input("A Name:")
number = input("A Number:")
sickness = input("A Sickness:")
adjective3 = input("An Adjective:")
adjective4 = input("An Adjective:")
plant = input("Plant:")
word_describing_size = input("Word describing size:")
verb_past_tense = input("A past tense verb:")
noun2 = input("A noun:")
noun3 = input("A noun:")
verb1 = input("A verb:")
store = input("A store name:")
noun4 = input("A noun:")
adjective5 = input("An Adjective:")
noun5 = input("A noun:")
verb_ending_in_ed = input("A verb ending in -ed:")
living_thing = input("A living thing:")
noun6 = input("A noun:")
noun7 = input("A noun:")
noun8 =input("A noun:")
verb_ending_in_ed2 = input("A verb ending in -ed")

print(f"\tThe woman was {adjective1} because she lost her {noun}.\n It was very {adjective2} to her because she {feeling_ending_in_ed} it.\n Her name is {name} and she is {number} years old.\n After she lost it, she fell very ill and developed {sickness}.\nThe sickness made her very {adjective3} for almost 50 days.\n On the 50th day, she felt {adjective4}.\n She looked at her arm, and there was {plant} growing on it!\n The plant grew bigger and bigger until it was {word_describing_size}!\n She {verb_past_tense} to the doctor, tripping on {noun2}and {noun3}.\n She {verb1} crossed the road, and fell over a root.\n She saw a {store.title()} and a {noun4}, but there was no doctor!\n She finally saw it, across a river of {adjective5} {noun5}!\n She {verb_ending_in_ed} across the river, but she was attacked by {living_thing}!\n  She grabbed onto {noun6}, {noun7} and {noun8}, but couldn't get away!\n So she promtly {verb_ending_in_ed2}.\n She died after, The End!") 